services:
    webserver:
        container_name: blog-serve
        build: .
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./uploads:/var/www/html/public/uploads
            - ./storage:/var/www/html/storage
            - /etc/letsencrypt:/etc/letsencrypt:ro
        environment:
            DB_CONNECTION: mysql
            DB_HOST: 172.17.0.1
            DB_PORT: 3306
            DB_DATABASE: larablog_db
            DB_USERNAME: henderson
            DB_PASSWORD: Ghost28012002

    phpmyadmin:
        container_name: blog-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: 172.17.0.1
            PMA_USER: henderson
            PMA_PASSWORD: Ghost28012002
        ports:
            - "8080:80"
